### ISSUE TITLE
A9hl+Luma3DS load ctruLua through HBL

### ISSUE THREAD

**Issue by HibernantBear** [ctruLua/ctruLua#11]
A9HL cracked New 3DS, using Luma3DS, system version is 11.4.0-37J.
Load ctruLua through the homebrew launcher.
It just stoped after some words blink over on top screen and some full single color display on bottom screen, stoped remain black up screen and red bottom screen

**Comment by Firew0lf** [comment]
We never tested CtrµLua  with another launching method than with the normal exploits ... Guess we should have. Also I have no testing platform with A9HL, nor 11.4.

What were the "words blinking" ? If it contained "FATAL ERROR" it may be related to CtrµLua's. Also, if something happens when pressing Start on the black/red screen, it may be either a missing "main.lua" file or a library that can't initialize (more likely this).

I'll upload a debug build today, so we will see where it fails.

**Comment by WhatNodyn** [comment]
I never had this issue with arm9loaderhax on 11.2.
I recently switched to 11.4 with boot9strap. I'll do some further testing on my side and report back.

By the way, arm9loaderhax is a normal exploit. In fact it's the most used one. Although everybody is slowly switching to sighax + boot9strap since their publication a few hours ago.

**Comment by WhatNodyn** [comment]
@Firew0lf : Just tested on OLD-11.4.0-37E with B9S(SigHax) and Luma3DS, booted on SysNAND.
The shell starts up fine. I'm going to see if I can have someone test it on New3DS with the same configuration. It might be a region issue or a New3DS issue.

@HibernantBear : I recommend that you upgrade to Luma3DS 7.1 and Sighax. It might fix your issues, and it looks like it's going to become the new standard anyway.

**Comment by Firew0lf** [comment]
I'll soon commit something to add CIA builds, currently it works but there are some other things to fix. It will be on the wip branch, so don't search it on master :p .

**Comment by HibernantBear** [comment]
well I didn't notice this for a long time, sorry about that. I'll have a tr. all yo. have mentioned above, but for luma3ds7.1 and sighax I don't think I'll proceed recently cause I still have my super mystery dungeon to play :p

**Comment by Firew0lf** [comment]
This is a debug screen from the *hax, not CtrµLua.
CIA builds are now available on the [CI server](https://ci.reuh.tk/ctrulua-wip), maybe you should try again with these. You don't have to reinstall/move anything of the ".lua" part, the `main.lua` file should be at `sdmc:/3ds/ctruLua/main.lua` just like with the 3dsx build.

(Also, the "wip" branch is stable enough, it's just that some functions may not be working well)

**Comment by HibernantBear** [comment]
ok, I'll have a try later, thank you very much
